spring.application.name=laba1

#mongo connection
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=security25

#security settings
#spring.security.user.name=admin
#spring.security.user.password=admin

#jwt settings
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

